"""Phase 5 distill — emit `~/.trinity/core.md`.

The five plural core memories (lens, picks, routing, topics, vocabulary) each
hold one *kind* of pattern. When the chairman synthesizes a new council, it
benefits from a single-paragraph distillation of them all rather than reading
every file from disk on every call.

`core.md` is that distillation. ~1 paragraph, generated by one flagship call,
read FIRST by every council's chairman. The chairman falls through to specific
memory files only when it needs more depth than `core.md` carries.

Cost: one flagship synthesis call per dream run (or per explicit
`trinity-local distill` invocation). Skips entirely if no memories exist yet.
"""
from __future__ import annotations

import json
from pathlib import Path

from .state_paths import (
    core_path,
    lens_path,
    picks_path,
    routing_path,
    topics_path,
    vocabulary_path,
)


def _read_text_if_exists(path: Path, limit_chars: int = 8000) -> str:
    if not path.exists():
        return ""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""
    return text[:limit_chars]


def _read_json_summary(path: Path, limit_entries: int = 12) -> str:
    """For JSON memory files, render a compact summary the chairman can read
    without us re-implementing each schema's verbose dataclass dump."""
    if not path.exists():
        return ""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return ""
    if isinstance(data, dict):
        items = list(data.items())[:limit_entries]
        return json.dumps(dict(items), indent=2)[:6000]
    if isinstance(data, list):
        return json.dumps(data[:limit_entries], indent=2)[:6000]
    return str(data)[:1000]


def _has_any_memory() -> bool:
    """Skip distill entirely if no memories exist yet (cold install)."""
    return any(
        p.exists()
        for p in (lens_path(), picks_path(), routing_path(), topics_path(), vocabulary_path())
    )


def build_distill_prompt() -> str:
    """Compose the chairman prompt for the Phase 5 distillation.

    The chairman gets each memory file content (capped). Its job is to
    emit ONE paragraph (~3–6 sentences) that subsumes them all. No JSON
    schema — just human-readable prose the next chairman will read
    on every council.
    """
    sections = [
        ("LENS — value memory (paired tensions; what you reject vs accept)",
         _read_text_if_exists(lens_path())),
        ("PICKS — procedural memory (your model picks per topic, with reasoning)",
         _read_json_summary(picks_path())),
        ("ROUTING — empirical memory (per-category provider track record)",
         _read_json_summary(routing_path())),
        ("TOPICS — semantic memory (clusters of subjects you ask about)",
         _read_json_summary(topics_path())),
        ("VOCABULARY — language memory (how you use specific words)",
         _read_text_if_exists(vocabulary_path())),
    ]
    non_empty = [(name, body) for name, body in sections if body.strip()]
    if not non_empty:
        return ""

    parts = [
        "You are distilling a user's accumulated 'core memories' into a single",
        "paragraph (~3–6 sentences). This paragraph will be read FIRST by every",
        "council chairman synthesizing future answers for this user.",
        "",
        "Write in second person ('You ship leverage over...', 'You compress over...').",
        "Concrete, declarative, no hedging. Subsume the five memories below",
        "into the simplest possible expression of *this user as a developer*.",
        "Do not list the memories or label them — just write the paragraph.",
        "Aim for the shape of a personal manifesto someone could put on a",
        "business card, not a summary report.",
        "",
        "Five core memories to subsume:",
        "",
    ]
    for name, body in non_empty:
        parts.append(f"## {name}")
        parts.append("")
        parts.append(body.strip())
        parts.append("")
    parts.append("Now emit the single-paragraph distillation. No preamble, no")
    parts.append("trailing notes — just the paragraph itself.")
    return "\n".join(parts)


def write_core(text: str) -> Path:
    """Persist the distillation to ~/.trinity/core.md."""
    path = core_path()
    path.write_text(text.strip() + "\n", encoding="utf-8")
    return path


def distill_via_chairman(*, provider: str = "claude") -> dict:
    """End-to-end Phase 5: load memories → chairman call → write core.md.

    Returns a small report dict (`{ok, provider, path, chars, skipped?, reason?}`).
    Cheap and idempotent — safe to call from dream or directly.
    """
    if not _has_any_memory():
        return {
            "ok": False,
            "skipped": True,
            "reason": "no core memories present yet — run lens-build + consolidate first",
        }
    prompt = build_distill_prompt()
    if not prompt:
        return {"ok": False, "skipped": True, "reason": "empty prompt (no readable memories)"}

    from pathlib import Path as _Path
    from .config import load_config
    from .providers import make_provider, ProviderError

    config = load_config()
    provider_config = config.providers.get(provider)
    if provider_config is None or not provider_config.enabled:
        return {"ok": False, "error": f"Unknown or disabled provider: {provider}"}

    runner = make_provider(provider_config)
    try:
        result = runner.run(prompt, _Path("."))
    except ProviderError as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}

    text = (result.stdout or "").strip()
    if not text:
        return {"ok": False, "error": "empty provider output"}

    path = write_core(text)
    return {
        "ok": True,
        "provider": provider,
        "path": str(path),
        "chars": len(text),
    }
