from __future__ import annotations

from pathlib import Path

from .scoreboard import state_dir
from .shortcuts_integration import DEFAULT_SHORTCUT_NAME


def shortcut_setup_dir() -> Path:
    path = state_dir() / "shortcut_setup"
    path.mkdir(parents=True, exist_ok=True)
    return path


def render_shortcut_setup_markdown(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> str:
    return f"""# {shortcut_name}

Create a macOS Shortcut named `{shortcut_name}` with this structure:

1. `Receive` text input.
2. `Get Dictionary from Input`.
3. `Get Dictionary Value` for key `name`.
4. `If` `name` is `run_command`:

   - `Get Dictionary Value` for key `args`
   - `Get Dictionary Value` from `args` for key `command`
   - `Run Shell Script` with:

```bash
/bin/zsh -lc "$1"
```

   Pass the `command` value as the first argument to the shell script.

5. Optional `Otherwise If` branches:

   - `name == open_review`
   - `name == start_council`
   - `name == workflow_create`
   - `name == open_path`
   - `name == open_url`
   - `name == run_applescript`

For the first version, you can simply map all of them to the equivalent shell
command generated by Trinity. The important thing is that `workflow_create`
becomes a first-class branch too, not an accidental fallback, because Trinity
uses it for workflow/Shortcut suggestions.

Optional:

6. `Get Dictionary Value` for key `task_id`.
7. `Get Dictionary Value` for key `metadata`.
8. `Show Notification` or `Quick Look` for debugging.

Example Trinity payload:

```json
{{"name":"open_review","args":{{"task_id":"task_123","path":"/Users/me/review.html"}},"task_id":"task_123","metadata":{{"kind":"review_ready"}}}}
```

Security note:

- This Shortcut executes whatever command Trinity passes to it.
- Keep it local to your Mac.
- Do not reuse it for untrusted URLs or arbitrary browser content.
"""


def write_shortcut_setup(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> Path:
    path = shortcut_setup_dir() / "TRINITY_DISPATCH_SETUP.md"
    path.write_text(render_shortcut_setup_markdown(shortcut_name), encoding="utf-8")
    return path
