from __future__ import annotations

import subprocess
from pathlib import Path

from .scoreboard import state_dir
from .shortcuts_integration import DEFAULT_SHORTCUT_NAME


def shortcut_setup_dir() -> Path:
    path = state_dir() / "shortcut_setup"
    path.mkdir(parents=True, exist_ok=True)
    return path


def render_shortcut_setup_markdown(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> str:
    return f"""# {shortcut_name}

Create a macOS Shortcut named `{shortcut_name}` with this structure:

1. `Receive` text input.
2. `Get Dictionary from Input`.
3. `Get Dictionary Value` for key `name`.
4. `If` `name` is `run_command`:

   - `Get Dictionary Value` for key `args`
   - `Get Dictionary Value` from `args` for key `command`
   - `Run Shell Script` with:

```bash
/bin/zsh -lc "$1"
```

   Pass the `command` value as the first argument to the shell script.

5. Optional `Otherwise If` branches:

   - `name == open_review`
   - `name == start_council`
   - `name == workflow_create`
   - `name == open_path`
   - `name == open_url`
   - `name == run_applescript`

For the first version, you can simply map all of them to the equivalent shell
command generated by Trinity. The important thing is that `workflow_create`
becomes a first-class branch too, not an accidental fallback, because Trinity
uses it for workflow/Shortcut suggestions.

Optional:

6. `Get Dictionary Value` for key `task_id`.
7. `Get Dictionary Value` for key `metadata`.
8. `Show Notification` or `Quick Look` for debugging.

Example Trinity payload:

```json
{{"name":"open_review","args":{{"task_id":"task_123","path":"/Users/me/review.html"}},"task_id":"task_123","metadata":{{"kind":"review_ready"}}}}
```

Security note:

- This Shortcut executes whatever command Trinity passes to it.
- Keep it local to your Mac.
- Do not reuse it for untrusted URLs or arbitrary browser content.
"""


def write_shortcut_setup(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> Path:
    path = shortcut_setup_dir() / "TRINITY_DISPATCH_SETUP.md"
    path.write_text(render_shortcut_setup_markdown(shortcut_name), encoding="utf-8")
    return path


def _render_installer_script(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> str:
    """Generate a shell script that creates the Trinity Dispatch shortcut.

    Uses the macOS `shortcuts` CLI to check if the shortcut exists.
    Since macOS doesn't support programmatic shortcut creation from shell,
    it opens the Shortcuts app for the user to create it manually.
    """
    return f'''#!/bin/zsh
# Trinity Dispatch Shortcut Installer
# Generated by trinity-local

set -e

SHORTCUT_NAME="{shortcut_name}"

echo "🔍 Checking for existing shortcut..."

if shortcuts list 2>/dev/null | grep -qF "$SHORTCUT_NAME"; then
    echo "✅ Shortcut '$SHORTCUT_NAME' already exists."
    echo "   Opening Shortcuts app for editing..."
    open "shortcuts://open-shortcut?name=$SHORTCUT_NAME"
    exit 0
fi

echo "📦 Creating shortcut '$SHORTCUT_NAME'..."
echo "   Note: macOS does not support programmatic shortcut creation."
echo "   Opening Shortcuts app — please create the shortcut manually."
echo ""
echo "   The setup guide has been written to:"
echo "   ~/.trinity/shortcut_setup/TRINITY_DISPATCH_SETUP.md"
echo ""

# Open Shortcuts app to the create screen
open "shortcuts://create-shortcut"

echo "✅ Shortcuts app opened. Follow the setup guide to configure."
echo ""
echo "   Quick steps:"
echo "   1. Name the shortcut: $SHORTCUT_NAME"
echo "   2. Add 'Receive Input' → text"
echo "   3. Add 'Get Dictionary from Input'"
echo "   4. Add 'Get Dictionary Value' → key 'name'"
echo "   5. Add 'If' branches for: run_command, open_review, start_council,"
echo "      workflow_create, open_path, open_url, run_applescript"
echo "   6. Each branch: Get args → Run Shell Script with the command"
echo ""
echo "   For details, see the full guide:"
echo "   open ~/.trinity/shortcut_setup/TRINITY_DISPATCH_SETUP.md"
'''


def write_installer_script(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> Path:
    """Write the installer shell script to the setup directory."""
    script = _render_installer_script(shortcut_name)
    path = shortcut_setup_dir() / "install_shortcut.sh"
    path.write_text(script, encoding="utf-8")
    path.chmod(0o755)
    return path


def run_installer(shortcut_name: str = DEFAULT_SHORTCUT_NAME) -> tuple[bool, str]:
    """Run the shortcut installer script.

    Returns (success, message).
    """
    # Write the setup guide first
    write_shortcut_setup(shortcut_name)
    script_path = write_installer_script(shortcut_name)

    try:
        result = subprocess.run(
            ["/bin/zsh", str(script_path)],
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = (result.stdout or "").strip()
        if result.returncode == 0:
            return True, output
        return False, (result.stderr or output or "Unknown error")
    except subprocess.TimeoutExpired:
        return False, "Installer timed out."
    except OSError as exc:
        return False, str(exc)
